import { describe, expect, it } from 'vitest';
import { SimulationEngine } from '../engine';
import { DEFAULT_CAST } from '../defaultCast';
import type { Agent, AgentType, Side } from '../types';

/**
 * SHORT SELLING & MARGIN.
 *
 * Every test here protects a rule a real broker enforces:
 *  - short capacity is collateralized by EQUITY, so short proceeds cannot finance the next short
 *  - short proceeds are restricted collateral, not spendable buying power
 *  - an underwater short is bought in (margin call), and covering BUYS shares back (conserved)
 *  - the user is a cash account unless shorting is explicitly enabled
 *
 * The engine uses Math.random, so nothing here asserts an exact price on a *populated* market.
 * The hand-built scenarios below use one deliberately INACTIVE market maker as the counterparty
 * (activity 0 → decideOrder returns no intents → the engine leaves its resting quotes alone),
 * which makes the price at which our own orders fill deterministic without touching src/.
 */

/** A market with a single passive counterparty whose seeded quotes survive step(). */
function counterpartyEngine(): { e: SimulationEngine; mm: Agent } {
  const e = new SimulationEngine();
  const mm = e.addAgent('marketMaker', 20_000_000, 'balanced', true);
  e.updateAgentParams(mm.id, { activity: 0 });
  return { e, mm };
}

/** Rest a quote directly in the book on the counterparty's behalf. */
function seedQuote(e: SimulationEngine, ownerId: string, side: Side, size: number, price: number): void {
  e.book.submitLimitOrder(side, size, price, ownerId, e.tick);
}

function fill(e: SimulationEngine, side: Side, size: number): void {
  e.queueUserOrder(side, size);
  e.flushUserOrders();
}

function buildDefaultEngine(): SimulationEngine {
  const e = new SimulationEngine();
  for (const c of DEFAULT_CAST) {
    const a = e.addAgent(c.type, c.capital, c.style);
    if (c.params) e.updateAgentParams(a.id, c.params);
  }
  return e;
}

const CAN_SHORT: AgentType[] = ['trader', 'dealer', 'marketMaker', 'arb'];

describe('short capacity is collateralized by equity, not cash', () => {
  // A short sale PAYS the seller, so cash rises. If capacity were sized off cash, every short
  // would enlarge the next one and short interest would compound without limit (the observed
  // 1,061 → 6,617 share runaway). Equity is flat across a short, so capacity must SHRINK by
  // roughly the shares sold. This is the single most important property in this file.
  it('a short sale consumes capacity rather than creating it', () => {
    const { e, mm } = counterpartyEngine();
    e.userCanShort = true;
    seedQuote(e, mm.id, 'buy', 5000, 100); // deep bid at the last price → price does not move

    const before = e.userMargin.shortCapacity;
    expect(before).toBeGreaterThan(0);

    fill(e, 'sell', 200);
    expect(e.user.shares).toBeCloseTo(-200, 6);
    expect(e.user.cash).toBeGreaterThan(100_000); // proceeds landed in cash...

    const after = e.userMargin.shortCapacity;
    // ...yet capacity fell by (about) the 200 shares sold, not rose.
    expect(after).toBeLessThan(before - 150);
    expect(after).toBeGreaterThan(before - 260);
  });

  it('repeated shorts do not compound capacity: total short interest stays inside the initial limit', () => {
    // Bug 5's signature was capacity GROWING with each short. At a constant price, the sum of
    // all shorts an account can ever open must stay bounded by its initial equity-based limit.
    const { e, mm } = counterpartyEngine();
    e.userCanShort = true;
    e.feeBps = 0; // isolate the collateral arithmetic from fee bleed
    seedQuote(e, mm.id, 'buy', 200_000, 100);

    const initialCapacity = e.userMargin.shortCapacity;
    const capacities: number[] = [initialCapacity];
    for (let i = 0; i < 25; i++) {
      fill(e, 'sell', 100);
      capacities.push(e.userMargin.shortCapacity);
    }

    // Monotone non-increasing (never regenerated by its own proceeds).
    for (let i = 1; i < capacities.length; i++) {
      expect(capacities[i]).toBeLessThanOrEqual(capacities[i - 1] + 1e-6);
    }
    // The position never exceeded the initial equity-based limit, and capacity CONVERGED
    // (the last few shorts bought no new room at all) instead of compounding.
    expect(-e.user.shares).toBeLessThanOrEqual(initialCapacity + 1);
    expect(capacities[capacities.length - 1]).toBeLessThanOrEqual(initialCapacity * 0.6);
    const tail = capacities.slice(-5);
    expect(Math.max(...tail) - Math.min(...tail)).toBeLessThan(1e-6);
    // Price never moved, so any growth in capacity could only have come from the proceeds.
    expect(e.currentPrice).toBeCloseTo(100, 6);
  });

  it('a fully-collateralized account is refused any further short', () => {
    // A blown-out account must not be able to keep selling short: the broker's collateral test
    // is what stops short interest growing without bound in a falling market. (The engine is
    // stricter still than raw capacity — it also nets off the existing short — so the position
    // settles at a fixed level and then the order is rejected outright.)
    const { e, mm } = counterpartyEngine();
    e.userCanShort = true;
    e.feeBps = 0;
    seedQuote(e, mm.id, 'buy', 500_000, 100);
    for (let i = 0; i < 40; i++) fill(e, 'sell', 500);

    const sharesBefore = e.user.shares;
    expect(sharesBefore).toBeLessThan(0);
    fill(e, 'sell', 500);
    expect(e.user.shares).toBeCloseTo(sharesBefore, 6);
    expect(e.lastOrderNote).toMatch(/short capacity/i);
  });
});

describe('buying power excludes restricted short proceeds', () => {
  // Short-sale proceeds are the broker's collateral for the buy-back, not funds to spend.
  // If they were spendable, a short would double as a leveraged long — free leverage.
  it('while short, buying power is below cash and never exceeds equity', () => {
    const { e, mm } = counterpartyEngine();
    e.userCanShort = true;
    seedQuote(e, mm.id, 'buy', 5000, 100);
    fill(e, 'sell', 400);

    const m = e.userMargin;
    expect(e.user.cash).toBeGreaterThan(m.equity); // cash is inflated by the proceeds
    expect(m.buyingPower).toBeLessThan(e.user.cash);
    expect(m.buyingPower).toBeLessThanOrEqual(m.equity + 1e-6);
    // ...but the restriction must not confiscate the account either: real equity stays
    // spendable. Without this a broken freeBuyingPower returning 0 would pass the bounds above.
    expect(m.buyingPower).toBeGreaterThan(0.9 * m.equity);
  });

  it('a market buy while short cannot spend the restricted proceeds', () => {
    // The purchase must be limited by real equity, so covering never overdraws the account.
    const { e, mm } = counterpartyEngine();
    e.userCanShort = true;
    e.feeBps = 0;
    seedQuote(e, mm.id, 'buy', 5000, 100);
    fill(e, 'sell', 900); // cash ≈ 190k, equity ≈ 100k
    seedQuote(e, mm.id, 'sell', 100_000, 100);

    const buyingPower = e.userMargin.buyingPower;
    fill(e, 'buy', 100_000); // ask for far more than it can afford
    const spent = 100 * (e.user.shares + 900);
    expect(spent).toBeLessThanOrEqual(buyingPower + 1);
    // ...and it really did buy: a rejected/zero-size order would satisfy the cap vacuously.
    expect(spent).toBeGreaterThan(0.9 * buyingPower);
    expect(e.user.cash).toBeGreaterThanOrEqual(0);
    expect(e.user.shares).toBeGreaterThan(-900); // covered part of the short with real equity
  });
});

describe('margin calls force covering', () => {
  it('an underwater short agent is bought fully back, and the shares come from the market', () => {
    // Maintenance margin is what turns a losing short into forced BUYING (the squeeze fuel).
    // Covering must be a real purchase — the shares are bought from a seller, not conjured.
    const { e, mm } = counterpartyEngine();
    seedQuote(e, mm.id, 'sell', 20_000, 100);
    const t = e.addAgent('trader', 100_000, 'value');
    // Hand-set an underwater short: equity 20k against 100k exposure (< 25% maintenance).
    e.updateAgentParams(t.id, { shares: -1000, cash: 120_000, avgCost: 100 });

    const floatBefore = e.sharesOutstanding;
    e.step();

    expect(t.shares).toBeGreaterThan(-1e-6); // fully covered, not halved
    expect(t.cash).toBeGreaterThan(0); // funded the buy-in
    expect(e.sharesOutstanding).toBeCloseTo(floatBefore, 6); // conserved through the cover
    expect(e.brokerWriteOffs).toBe(0); // it could pay: no broker injection
  });

  it('a market maker keeps quoting through its own margin call', () => {
    // A maker dropping out of the book is worse for the market than its own inventory problem;
    // the book must stay two-sided while it covers.
    const { e, mm } = counterpartyEngine();
    seedQuote(e, mm.id, 'sell', 20_000, 100);
    const maker = e.addAgent('marketMaker', 200_000, 'balanced');
    e.updateAgentParams(maker.id, { shares: -2000, cash: 230_000, activity: 1 });

    e.step();

    expect(maker.shares).toBeGreaterThan(-1e-6); // covered
    expect(e.book.countOrdersByOwner(maker.id)).toBeGreaterThan(0); // still quoting
  });

  it("the user's short is bought in when a rally wipes out the collateral", () => {
    const { e, mm } = counterpartyEngine();
    e.userCanShort = true;
    e.feeBps = 0;
    seedQuote(e, mm.id, 'buy', 5000, 100);
    fill(e, 'sell', 500); // short 500 @ 100, equity 100k vs 50k exposure — comfortable

    // The stock triples. Depth at the new price so the buy-in can actually execute.
    seedQuote(e, mm.id, 'sell', 20_000, 300);
    fill(e, 'buy', 1); // prints 300
    expect(e.currentPrice).toBeCloseTo(300, 6);
    expect(e.userMargin.marginCall).toBe(true);

    e.step();

    expect(e.user.shares).toBeGreaterThan(-1e-6); // bought in
    expect(e.userMargin.marginCall).toBe(false);
    expect(e.lastOrderNote).toMatch(/margin call/i);
  });

  it('a margin-called account is left with no stale resting orders', () => {
    // Covering cancels the account's quotes first: a forced buy-in must not leave working
    // orders that would re-open the very exposure being liquidated.
    const { e, mm } = counterpartyEngine();
    seedQuote(e, mm.id, 'sell', 20_000, 100);
    const t = e.addAgent('trader', 100_000, 'value');
    e.updateAgentParams(t.id, { shares: -1000, cash: 120_000, avgCost: 100, activity: 0 });
    seedQuote(e, t.id, 'sell', 50, 130); // a stale offer of its own

    e.step();

    expect(t.shares).toBeGreaterThan(-1e-6);
    expect(e.book.countOrdersByOwner(t.id)).toBe(0);
  });
});

describe('the user is a cash account unless shorting is enabled', () => {
  it('a sell with no holdings does not go short, and explains why', () => {
    const { e, mm } = counterpartyEngine();
    seedQuote(e, mm.id, 'buy', 5000, 100);
    expect(e.userMargin.canShort).toBe(false);
    expect(e.userMargin.shortCapacity).toBe(0);

    fill(e, 'sell', 250);

    expect(e.user.shares).toBe(0);
    expect(e.lastOrderNote).toMatch(/enable shorting/i);
  });

  it('a sell larger than the position is capped to the shares held', () => {
    // A cash account can only deliver what it owns; oversell would silently fabricate stock.
    const { e, mm } = counterpartyEngine();
    e.feeBps = 0;
    seedQuote(e, mm.id, 'sell', 5000, 100);
    fill(e, 'buy', 300);
    expect(e.user.shares).toBeCloseTo(300, 6);

    seedQuote(e, mm.id, 'buy', 5000, 100);
    const floatBefore = e.sharesOutstanding;
    fill(e, 'sell', 5000);

    expect(e.user.shares).toBeCloseTo(0, 6);
    expect(e.user.shares).toBeGreaterThanOrEqual(0);
    expect(e.sharesOutstanding).toBeCloseTo(floatBefore, 6);
  });

  it('resting sell orders reserve the shares, so the user cannot sell the same stock twice', () => {
    const { e, mm } = counterpartyEngine();
    e.feeBps = 0;
    seedQuote(e, mm.id, 'sell', 5000, 100);
    fill(e, 'buy', 300);

    // Two resting offers above the market, each for the whole position.
    e.queueUserOrder('sell', 300, 120);
    e.flushUserOrders();
    e.queueUserOrder('sell', 300, 121);
    e.flushUserOrders();

    // The first offer must actually be working (else "no double-sell" is vacuously true),
    // and the second must have found nothing left to reserve.
    expect(e.book.restingSellSize('user')).toBeGreaterThan(299);
    expect(e.book.restingSellSize('user')).toBeLessThanOrEqual(300 + 1e-6);
  });

  it('enabling shorting is what unlocks a short sale', () => {
    const { e, mm } = counterpartyEngine();
    seedQuote(e, mm.id, 'buy', 5000, 100);
    fill(e, 'sell', 200);
    expect(e.user.shares).toBe(0);

    e.userCanShort = true;
    expect(e.userMargin.shortCapacity).toBeGreaterThan(0);
    fill(e, 'sell', 200);
    expect(e.user.shares).toBeLessThan(-1);
  });
});

describe('shorting across a full simulation', () => {
  const e = buildDefaultEngine();
  const startCash = e.agents.reduce((s, a) => s + a.cash, 0) + e.user.cash + e.optionsDealer.cash;
  const startFloat = e.sharesOutstanding;
  const TICKS = 3000;
  const minSharesByType = new Map<AgentType, number>();
  let worstNonShorter = Infinity;
  let peakShortInterest = 0;
  let sawShort = false;

  for (let i = 0; i < TICKS; i++) {
    e.step();
    const si = e.agents.reduce((s, a) => s + Math.max(0, -a.shares), 0);
    if (si > peakShortInterest) peakShortInterest = si;
    if (si > 0) sawShort = true;
    for (const a of e.agents) {
      const prev = minSharesByType.get(a.type);
      if (prev == null || a.shares < prev) minSharesByType.set(a.type, a.shares);
      if (!CAN_SHORT.includes(a.type)) worstNonShorter = Math.min(worstNonShorter, a.shares);
    }
  }

  it('only the archetypes permitted to short ever hold a negative position', () => {
    // Borrowing stock is a privilege of specific participants. A long-only fund going
    // negative would mean the engine is creating shares out of nothing on the sell side.
    expect(worstNonShorter).toBeGreaterThan(-1e-6);
    for (const [type, min] of minSharesByType) {
      if (!CAN_SHORT.includes(type)) expect(min).toBeGreaterThan(-1e-6);
    }
  });

  it('short interest stays a bounded fraction of the float', () => {
    // Real short interest is a slice of the float, not a multiple of it. Unbounded short
    // interest is the observable symptom of self-financing shorts.
    // Bound the PEAK over the whole run, not just the end state (a runaway that unwound
    // before tick 3000 would otherwise be invisible). Observed peaks are 7-13% of the
    // float; heavily-shorted real names top out around 30%, which is the bound used here.
    expect(peakShortInterest).toBeLessThan(0.3 * startFloat);
    // ...and there WAS short interest, so the bound is a real constraint, not an empty set.
    expect(sawShort).toBe(true);
    expect(peakShortInterest).toBeGreaterThan(0.001 * startFloat);
  });

  it('every account is still solvent after a long run of shorting and squeezes', () => {
    // A market where participants carry negative equity is one that has been fabricating
    // money; forced covering must happen before an account goes underwater.
    const px = e.currentPrice;
    const insolvent = e.agents.filter((a) => a.cash + a.shares * px <= 0);
    expect(insolvent.map((a) => a.name)).toEqual([]);
  });

  it('shorting and covering never fabricate cash', () => {
    // The whole point of equity-based capacity: cash may only change through dividends
    // (in), fees (out) and recorded broker write-offs. Shorts must be cash-neutral.
    const endCash = e.agents.reduce((s, a) => s + a.cash, 0) + e.user.cash + e.optionsDealer.cash;
    const expected = e.totalDividendsPaid - e.totalFeesPaid + e.brokerWriteOffs;
    expect(Math.abs(endCash - startCash - expected)).toBeLessThan(Math.abs(startCash) * 1e-9 + 1e-6);
  });

  it('the float is conserved despite shorts going negative', () => {
    // Short sales move existing shares; they do not mint them. NOTE: comparing
    // `sharesOutstanding` to the sum of holdings would be a tautology — the getter IS that
    // sum. The only non-circular statement is that the total is the SAME as before the run.
    expect(e.sharesOutstanding).toBeCloseTo(startFloat, 6);
    // Someone genuinely went negative, so conservation was exercised across shorts.
    expect(Math.min(...minSharesByType.values())).toBeLessThan(-1);
  });
});

describe('the agent margin call: it works, but is unreachable and uncapped', () => {
  /**
   * Real-market property: a short whose equity falls below the maintenance requirement is
   * forced to buy back, and that forced buying is what turns a rising market into a SHORT
   * SQUEEZE. The engine implements this (full buy-in below MAINT_MARGIN x exposure) and the
   * first test confirms the mechanism fires.
   *
   * Two documented problems follow it.
   */
  function build() {
    const e = new SimulationEngine();
    e.autoNews = true;
    for (const c of DEFAULT_CAST) {
      const a = e.addAgent(c.type, c.capital, c.style);
      if (c.params) e.updateAgentParams(a.id, c.params);
    }
    e.enableOptions(true);
    for (let t = 0; t < 1500; t++) e.step();
    return e;
  }

  it('force-covers a short that falls below the maintenance requirement', () => {
    const e = build();
    const px = e.currentPrice;
    const a = e.agents.find((x) => x.type === 'trader')!;
    // Underwater: exposure far above equity, so it is already past the call threshold.
    a.shares = -3000;
    a.cash = 3000 * px * 0.3;
    const floatBefore = e.sharesOutstanding;

    e.step();

    // The borrow must be returned: the position is closed, not left dangling.
    expect(a.shares).toBeGreaterThan(-0.05);
    // And covering is a real purchase from real sellers, so shares stay conserved.
    expect(e.sharesOutstanding).toBeCloseTo(floatBefore, 0);
  });

  it('never leaves a margin-called agent overdrawn, and records the deficit', () => {
    // Real-market property: an account cannot pay for a buy-in with money it does not have.
    // The buy-in itself is deliberately NOT capped by cash — the borrowed stock must be returned
    // and a half-finished liquidation leaves a phantom short — so instead the broker absorbs any
    // deficit and it is recorded, exactly as for an unfundable wind-down. Before this, the
    // margin-call path was the one purchase path in the engine with neither a funding check nor
    // a write-off branch, and it ran a 3,000-share short to -$201k.
    const e = build();
    const px = e.currentPrice;
    const a = e.agents.find((x) => x.type === 'trader')!;
    a.shares = -3000;
    a.cash = 3000 * px * 0.3; // nowhere near enough to buy 3,000 shares back
    const writeOffsBefore = e.brokerWriteOffs;

    e.step();

    // Covered in full (the borrow is returned) and NOT overdrawn.
    expect(a.shares).toBeGreaterThan(-0.05);
    expect(a.cash).toBeGreaterThan(-1);
    // The cash the broker had to put in is visible rather than conjured.
    expect(e.brokerWriteOffs).toBeGreaterThan(writeOffsBefore);
  });

  it('never reaches a margin call under its own dynamics — the squeeze is unreachable', () => {
    // Documents a REALISM GAP rather than a crash, and the cause is NOT the margin rules.
    // Measured: raising short margin capacity to Reg T 2x and then raising the short exposure
    // cap to 1.6x and 2.2x equity all produced 0 calls. The actual blockers are that price sits
    // BELOW fair value on 100% of ticks so traders want any short only 5.8% of the time, and
    // that they rebalance continuously and cover VOLUNTARILY before equity erodes to 25%.
    // A squeeze needs a stubborn levered short held through a rising market, which no archetype
    // provides — and it cannot enter one anyway while the market never trades at a premium.
    // This reduces to the persistent-discount defect (see CLAUDE.md), the same root cause as
    // bubbles being inexpressible.
    //
    // The assertion is deliberately the OBSERVED behaviour, so that if the model ever does start
    // producing margin calls naturally this test fails and someone re-reads this comment. That
    // would be an improvement in realism, not a regression.
    const e = build();
    let calls = 0;
    for (let t = 0; t < 4000; t++) {
      const px = e.currentPrice;
      for (const a of e.agents) {
        if (a.shares < -0.05) {
          const exposure = -a.shares * px;
          if (a.cash + a.shares * px < 0.25 * exposure) calls++;
        }
      }
      e.step();
    }
    expect(calls).toBe(0);
  });
});
